-- =====================================================
-- Teacher's Terminology Migration
-- Source: geography_glossary_merged.xlsx
-- =====================================================

-- Create teacher_definitions table if not exists
CREATE TABLE IF NOT EXISTS teacher_definitions (
    id SERIAL PRIMARY KEY,
    topic_id VARCHAR(10) NOT NULL,
    term VARCHAR(255) NOT NULL,
    definition TEXT NOT NULL,
    theme VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Clear existing teacher definitions
DELETE FROM teacher_definitions;

-- TOPIC 1.1: 1.1 Population Dynamics
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Ageing population', 'An increase in the proportion of older (over the age of 65) people.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Anti-natalist policy', 'A government policy to slow down a country''s fertility rate by imposing limits on childbirth.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Crude birth rate (CBR)', 'The number of live birth rates per 1000 people per year, usually calculated for a country.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Crude death rate (CDR)', 'The number of deaths per 1000 people per year, usually calculated for a country.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Demographers', 'People who study the human population. Demography is the study of human populations.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Dependents', 'People who are not part of the labour force of a country. This includes young dependents (those aged 0‚Äì14) and elderly dependents (those aged 65 and above).', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Economically active', 'People aged 15‚Äì64, who are usually working and providing resources to dependents.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Fertility rate', 'The average number of children a woman gives birth to during her lifetime.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Infant mortality rate', 'The number of deaths of infants under one year old per 1000 live births per year.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Natural increase', 'The difference between the CBR and CDR. It can be recorded either as a net change per 1000 people or as a percentage.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Population explosion', 'A sudden increase in the number of people in a specific area at a given time.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Population momentum', 'When growing populations continue growing even after the fertility rate declines, due to the population''s young age distribution.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Population policy', 'An action taken by a country''s government to influence the size of the population.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Population pyramid', 'A type of bar chart used to show the proportion of males and females belonging to different age groups for a place or a country.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Population structure', 'The make-up of a population in terms of age, sex, occupation, ethnicity or any other selected criteria.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Pro-natalist policy', 'A government policy to encourage people to have more children.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Replacement level fertility', 'The level of fertility at which a population exactly replaces itself from one generation to the next. In HICs, replacement level fertility can be taken as requiring an average of 2.1 children per woman.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.1', 'Youthful population', 'A country which has a high proportion of young (under the age of 15) people.', 'Population and Settlement');
-- TOPIC 1.2: 1.2 Migration
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Destination country', 'In international migration, the country which migrants are moving to.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Displacement', 'The forced movement of people caused by factors such as natural disasters, famine, diseases, or conflict.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Economic migrant', 'A person seeking work in another country.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Emigrant', 'A person who leaves their country of origin to live in another country permanently.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Immigrant', 'A person who moves to a foreign country to live there permanently.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'International migration', 'The permanent movement of people from one country to another country.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Migration', 'The movement of people from one area to another. This may be temporary or permanent and may be international or within a country.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Net migration', 'The balance between immigration and emigration numbers for a particular country.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Origin country', 'In international migration, the country which migrants are moving from.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Pull factor', 'The perceived positive factors that encourage people to move to a place.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Push factor', 'Negative factors that encourage or force people to move from a place.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Remittances', 'The money or goods that migrants send back to families and friends in origin countries.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.2', 'Voluntary migration', 'When someone chooses to move usually for better opportunities.', 'Population and Settlement');
-- TOPIC 1.5: 1.5 Settlements & Service Provision
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.5', 'Dispersed settlement', 'A settlement that is spread out, usually rural.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.5', 'Linear settlement', 'A settlement that follows roadways, railways, valleys, or coastlines.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.5', 'Nucleated settlement', 'A settlement that is clustered around a central point, such as a religious building or a road intersection.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.5', 'Rural settlement', 'A settlement area with low population density in the countryside.', 'Population and Settlement');
-- TOPIC 1.6: 1.6 Urban Settlements
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Bottom-up development', 'Urban management schemes planned by small, non-government organisations often involving local people.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Brownfield sites', 'Land within an urban area that has been abandoned and unused.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Counter-urbanisation', 'The movement of people away from towns and cities to the countryside.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Gentrification', 'A process where the character of a poor urban area is changed by wealthier people and businesses moving in.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Green infrastructure', 'Natural spaces in towns and cities designed to deliver benefits for people and the environment. Includes street trees, green roofs, parks, and wildlife areas.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Greenfield sites', 'An area of land usually found on the edge of a large town or city that has not been developed previously.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Informal sector', 'People who earn a living through self employment that is unregulated by the government. They are not on payrolls and are not taxed.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Informal settlement', 'Any form of housing, shelter, or settlement where the people have no legal rights to the land they are built upon.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Self-help scheme', 'An urban management strategy that involves residents by providing them with building materials, tools, and training that they use to construct and improve their homes.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Suburbanisation', 'The movement of people and services from the centre to the edge of towns and cities (the suburbs).', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Sustainable urban management', 'A city''s use of resources and space in a way that meets the needs of its residents today without negatively impacting residents'' needs in the future.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Top-down development', 'Urban management schemes planned by the government.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Urban growth', 'An increase in the population size and/or physical extent of an urban place.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Urban inequality', 'The unequal distribution of resources and opportunities between people living in towns and cities.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Urban settlement', 'A built-up human settlement that forms a town or a city.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.6', 'Urban sprawl', 'The unplanned growth of urban areas into the surrounding countryside.', 'Population and Settlement');
-- TOPIC 1.7: 1.7 Urbanisation
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.7', 'Rural-urban fringe', 'The area where the countryside meets the built-up part of towns and cities.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.7', 'Urbanisation', 'An increase in the proportion of people living in towns and cities.', 'Population and Settlement');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('1.7', 'Urbanisation pathway', 'The stages in urbanisation that countries typically experience where they become more urban as they develop economically.', 'Population and Settlement');
-- TOPIC 2.1: 2.1 Earthquakes & Volcanoes
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Aftershocks', 'A smaller earthquake that comes after the main shock of a large earthquake.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Conservative/transform plate boundary', 'A plate boundary where two plates are moving past each other.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Convection currents', 'The movement of heat from one place to another by the mass movement of molten rock.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Convergent plate boundary', 'A plate boundary where two tectonic plates are moving towards each other.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Core', 'The very hot, very dense, solid centre of the Earth.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Coriolis effect', 'The force exerted by the Earth as it spins. It is greatest nearer the poles and weakest at the Equator.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Crater', 'A bowl or funnel shaped depression that usually lies directly above the vent from which volcanic material is ejected.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Crust', 'The outermost layer of the Earth, made up of solid rock.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Divergent/constructive plate boundary', 'A plate boundary where two tectonic plates are moving apart from each other.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Earthquake', 'A sudden violent shaking of the ground caused by movement within the Earth''s crust or volcanic activity.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Epicentre', 'The point above the focus, where the earthquake first reaches the surface.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Focus/origin', 'The point, below the Earth''s surface, where an earthquake originates.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Hazard mapping', 'The creation of maps that highlight areas that are vulnerable to a particular hazard.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Lahar', 'A destructive mudflow on the slopes of a volcano.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Lithosphere', 'The rigid outer layer of the earth, made up of the crust and the upper mantle.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Magma', 'Hot, melted rock that is fluid or semi-fluid, below or within the Earth''s crust.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Magma chamber', 'The location beneath the vent of a volcano where molten rock is stored before an eruption.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Mantle', 'The largest layer of the Earth''s structure, found between the crust and the outer core. It is made up of the outer and inner mantle and varies in temperature.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Primary response', 'The immediate and short-term reaction to a natural disaster.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Pyroclastic', 'A fast-moving current of hot gas and volcanic matter that flows along the ground. It flows away from the volcano at average speeds of over 100km/h and up to speeds of 700km/h.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Secondary response', 'The long-term reaction to a natural disaster.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Seismic waves', 'Shockwaves or concentric rings of energy that travel through or over the Earth.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Seismograph', 'An instrument that records the seismic waves caused by an earthquake.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Subduction', 'When one tectonic plate sinks beneath another tectonic plate due to differences in density.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Tectonic plate', 'A large, irregularly shaped section of the lithosphere. There are seven major tectonic plates.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Tephra', 'Rock fragments and particles ejected by a volcanic eruption.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Vent', 'The place on the Earth''s surface where lava flows from, and where fragmented rocks erupt.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.1', 'Volcano', 'A mountain or hill that has a crater or vent. Lava, rock fragments, hot vapour, and gas erupt through the crater or vent, and through the Earth''s crust.', 'The Natural Environment');
-- TOPIC 2.2: 2.2 Rivers
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Abrasion', 'When the load of a river rubs against the riverbed and riverbanks, wearing them down over time.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Alluvium', 'River sediments, such as silt and mud.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Attrition', 'When particles carried by a river/sea collide and break into smaller pieces.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Centrifugal force', 'A force that causes a river flowing around a bend to move out and away from the centre of the channel.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Channelisation', 'Straightening, widening, or deepening rivers so that they can hold more water.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Corrasion', 'Material carried by the sea rubs against cliffs, wearing them away.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Delta', 'A depositional landform found at the mouth of a river.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Discharge', 'The volume of river water flowing past a given point at a given time.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Distributaries', 'Smaller channels that flow away from the main river, often found in deltas.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Drainage basin', 'An area of land that is drained by a single river and its tributaries.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Floodplain', 'A flat area of land found beside rivers in the middle and lower course.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Floodplain zoning', 'Ensuring land uses that are temporary or of lower value lie beside the river where there is greater risk of flood.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Gorge', 'A narrow valley that forms when a waterfall retreats upstream.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Hard engineering', 'Flood management techniques that work against nature.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Hydraulic action', 'When the force of moving water removes rocks and sediment from the riverbed/seabed and riverbanks.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Levee', 'Higher areas of land found beside a river.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Meander', 'A bend in a river, usually found in the lower or middle courses.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Mouth', 'The end of a river, sometimes found where the river enters the sea.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Oxbow lake', 'An isolated section of water that is left behind when a meander bend becomes cut off.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Potholes', 'Cylindrical depressions in a riverbed created by abrasion.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Rapids', 'Steep sections of a river where shallow, fast flowing water lead to turbulence.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'River restoration', 'Reversing changes that humans have made to the river to reduce flood risk downstream.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Saltation', 'When small pebbles and stones appear to bounce along the riverbed/seabed.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Soft engineering', 'Flood management techniques that work alongside nature.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Solution (erosion)', 'A form of erosion which occurs when chemicals in the river water dissolve certain rock types, like limestone.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Solution (transportation)', 'A form of transportation which occurs when soluble minerals from rocks and sediments are dissolved within the water.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Source', 'The start of a river, usually in highland areas.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Suspension', 'When fine sediment particles, such as silt and clay, are carried along by the river/sea.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Traction', 'When large boulders and rocks are pushed, dragged, or rolled along the riverbed/seabed by the force of flowing water.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Waterfall', 'Water flowing over a ledge of harder rock.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.2', 'Wetted perimeter', 'The part of the river channel that is in direct contact with the water in the river, for example, the riverbed and banks.', 'The Natural Environment');
-- TOPIC 2.3: 2.3 Coasts
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Arch', 'A landform created when the sea erodes through a headland.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Backwash', 'The movement of water back down the beach by gravity.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Bar', 'A submerged, or partly submerged, ridge of sediment that forms offshore, parallel to the shoreline.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Bay', 'A curved indentation of the coastline formed by the erosion of softer rock.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Beach', 'An accumulation of sand or shingle between land and sea.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Cave', 'A hollow in a cliff caused by erosion.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Cliff', 'A steep rock face.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Concordant coastline', 'A coastline where different rock type runs parallel to the shoreline.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Constructive waves', 'Waves with a long wavelength, low frequency and low wave height that deposit material and build up a beach.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Corrosion', 'The slightly acidic nature of sea water breaks down material. Chalk and limestone cliffs are particularly prone to this.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Destructive waves', 'Waves with a short wavelength, high frequency and high wave height that remove material from a beach.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Discordant coastline', 'A coastline where different rock types run perpendicular to the shoreline.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Fetch', 'The distance of the sea that the wind blows over to generate waves.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Headland', 'A piece of land, usually with steep cliffs, that sticks out into the sea further than the surrounding coastline. It is made of harder rock than the surrounding area.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Longshore drift', 'The process that transports sediment along a coastline due to the swash and backwash of waves.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Sand dune', 'A mound or ridge of wind-blown sand.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Shoreline Management Plan (SMP)', 'A strategy for managing erosion and flood risk along a particular stretch of coastline.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Spit', 'A long, narrow accumulation of sand or shingle that sticks out from the mainland into the sea.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Stack', 'A tall column of rock formed when the roof of an arch collapses.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Storm surge', 'An abnormal rise in sea level during a tropical storm, caused by strong winds and low-pressure pushing water onshore.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Stump', 'A short column of rock formed by the erosion of a stack.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Swash', 'The movement of a breaking wave up the beach.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Wave frequency', 'The amount of time taken for a wave to pass through one wavelength.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Wave height', 'The distance between a wave trough and wave crest.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Wave refraction', 'Waves bending to fit the shape of the shoreline as they encounter shallow water.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Wave-cut platform', 'A flat, gently sloping rock ledge found at the base of a cliff. It is created by the erosion and retreat of a cliff over time.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.3', 'Wavelength', 'The distance between two wave crests.', 'The Natural Environment');
-- TOPIC 2.4: 2.4 Weather
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Climate', 'The typical or average prevailing weather conditions in an area.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Cold snap', 'A short period of cold weather compared to expected conditions.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Condense', 'The process by which water vapour becomes liquid, by cooling or where humidity level is too high for the air to hold more water.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Convectional rainfall', 'When air heated at the Earth''s surface rises upwards, taking water vapour with it. This condenses to form clouds.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Diurnal', 'A pattern that occurs every 24 hours. A diurnal temperature range refers to the difference between daytime and nighttime temperatures.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Drought', 'A prolonged period of abnormally low rainfall in an area. Drought can last for days, weeks, or even years.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Heatwave', 'An extended period of hot weather compared to expected conditions.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Insolation', 'Incoming solar radiation.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Monsoon', 'A reversal of the prevailing winds in an area which causes a change in rainfall patterns.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Precipitation', 'Water falling from the air onto the land, for example, rain, snow, and hail.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Thermal expansion', 'An increase in the volume of water as a result of heating.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Tropical storm', 'A storm system of strong winds and heavy rainfall that forms over warm ocean waters.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.4', 'Tsunami', 'High sea waves caused by an earthquake.', 'The Natural Environment');
-- TOPIC 2.5: 2.5 Climate & Natural Vegetation
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Abiotic', 'The element of an ecosystem that is non-living or without life. For example, climate, soil type, and slope angle are all abiotic factors that influence the structure of an ecosystem.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Biotic', 'The elements of an ecosystem that are living organisms, such as plants and animals.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Climate justice', 'Treating everyone fairly in addressing climate change, considering past inequalities.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Climate refugee', 'A person who has been forced to leave their home due to the impacts of climate change.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Coral bleaching', 'The loss of vibrant colours in coral due to expelled algae, triggered by stressors like high sea temperatures. Long-term bleaching can kill coral and reduce reef biodiversity.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Coral reef', 'An underwater ecosystem formed by an accumulation of calcium carbonate produced by coral polyps.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Deforestation', 'Cutting down trees and clearing an area of forest.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Ecosystem', 'A biological community of organisms interacting with each other and the physical environment.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Geology', 'The type of rock found within a given area.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Habitat', 'The natural home of an animal, plant, or other organism.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Mangroves', 'Salt-tolerant trees or shrubs that grow in brackish water along tropical and subtropical coastlines.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Marine ecosystems', 'Ecosystems in waters that have high salt content.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Marine protected area (MPA)', 'An area of the ocean established to protect habitats and species that are essential for healthy marine ecosystems.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Rainforest degradation', 'The removal or thinning of areas of rainforest.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Reforestation', 'Replanting trees in an area where they have previously been cut down.', 'The Natural Environment');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('2.5', 'Terrestrial ecosystems', 'Ecosystems of or on land.', 'The Natural Environment');
-- TOPIC 3.1: 3.1 Development
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Aid', 'Assistance given from one country to another, such as money, equipment, or training.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Bilateral aid', 'Strategic support, whereby the recipient country must spend the money on goods or services from the donor country.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Development', 'An improvement in the standard of living and quality of life for the population of a country.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Development gap', 'The difference in levels of development between HICs and LICs.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Development pathway', 'The development progress of a country over time.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Economic indicators', 'Measures of development that affect the economy, such as average income.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'High-Income Countries (HICs)', 'Classified by the World Bank (in 2022) as a country with a gross national income per capita of $13846 or more.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Human Development Index (HDI)', 'A composite measure of development, combining measures of education, health, and income per capita.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Long-term aid', 'Continuous support programmes that aim to bring benefit to the recipient country.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Low-Income Countries (LICs)', 'Classified by the World Bank (in 2022) as a country with a gross national income per capita of $1135 or less (in 2022).', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Middle-Income Country (MIC)', 'Classified by the World Bank as a country with a gross national income per capita between $1136 and $13845 in 2022.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Multilateral aid', 'High-income countries donate money to international organisations, to be distributed among poorer countries.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Quality of life', 'The general wellbeing of people, measured using factors such as a person''s happiness, level of health, and political freedoms.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Short-term aid', 'Immediate support provided during or after a disaster such as famine or an earthquake.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Social indicators', 'Measures of development that affect people, such as life expectancy or calorie intake.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.1', 'Standard of living', 'The material goods and levels of comfort people have, measured using factors such as income, employment opportunities, and affordable access to healthcare.', 'Economic Development ');
-- TOPIC 3.2: 3.2 Food Production
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Aeroponics', 'A technique of growing plants with the roots suspended in air, while nutrient solution is delivered to them in the form of a fine mist.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Aquaponics', 'The hydroponics technique of growing plants with the addition of fish in the system, and fish waste used as the nutrient for the plants.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Arable farming', 'Farming with crops.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Calorie intake', 'The amount of energy obtained from food.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Commercial farming', 'Growing food on a large scale for profit.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Crop yield', 'The amount of agricultural product harvested in a given time.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Food aid', 'Help in the form of basic food items given to a country or region suffering from food shortages.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Food insecurity', 'When a person does not have access to sufficient, affordable, or healthy food to meet their basic needs for an active lifestyle.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Genetically modified (GM)', 'Crops generated from plants that have been genetically modified by scientists through the addition of new DNA to give the plant different characteristics, such as resistance to a specific disease.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'High-yield variety (HYV)', 'Crops that have a high yield potential and resistance to factors such as insects, diseases, floods and drought.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Hydroponics', 'A technique of growing plants in sand, gravel or liquid (not soil) with added nutrients.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Inputs', 'The factors put into a farming system. For example, capital inputs, physical inputs, and human inputs.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Irrigation', 'Supplying water for crops.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Malnutrition', 'Lack of adequate nutrition, caused by not having a balanced diet, or enough food to eat.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Mixed farming', 'Farming with both crops and livestock.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Monocropping', 'The process of growing the same crop year after year on the same land.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Outputs', 'The products that come out of the farming system. For example, crops, milk, meat.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Pastoral farming', 'Farming with livestock.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Processes', 'The activities that take place during the farming. For example, ploughing, milking, planting.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.2', 'Subsistence farming', 'Growing food to feed the family, rather than for profit.', 'Economic Development ');
-- TOPIC 3.3: 3.3 Industry
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Containerisation', 'A method of transporting freight (goods) by placing it in large containers of a standard size.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Corporate Social Responsibility (CSR)', 'Social and environmental policies and programmes which TNCs include in their operations.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Global industrial shift', 'The trend of manufacturing processes moving away from HICs to new industrialised centres.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Global supply chain', 'The worldwide network TNCs use when producing goods or services.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Globalisation', 'The process of increased connection between countries, especially in economics, politics, and culture.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Globalisation of food supplies', 'Where food is moved from the country it is produced in and sold in another country.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Industrialisation', 'When a country or area builds factories and begins to manufacture products.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Primary sector', 'The part of a country''s economy that produces raw materials and agricultural goods.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Quaternary sector', 'The part of a country''s economy that provides knowledge-based services, where workers require higher education and specialist skills.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Raw materials', 'Materials, such as cotton, that can be converted into a new product through the process of manufacturing.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Secondary sector', 'The part of a country''s economy that involves processing raw materials into a more valuable manufactured item.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Tertiary sector', 'The part of a country''s economy that provides a service to others.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Transnational corporations (TNCs)', 'Large companies (or groups of companies) involved in the international production of goods or services, across multiple countries. TNCs often base their headquarters in a HIC and their factories and service hubs in LICs.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Underemployment', 'When individuals are employed but their job does not fully utilise their skills and qualifications. This can result in part-time work, low wages, or jobs below their skill level.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.3', 'Unemployment', 'Individuals who do not have a job but are actively seeking and available for work.', 'Economic Development ');
-- TOPIC 3.4: 3.4 Tourism
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.4', 'Acculturation', 'Social, cultural, and psychological adaptation of a population that results from contact with the cultures and behaviours of visitors.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.4', 'Butler model', 'A model to study and predict how tourist resorts change over time.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.4', 'Carrying capacity', 'The maximum amount of people a resort or area can manage before negatively affecting the environment and the quality and availability of services.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.4', 'Ecotourism', 'A tourism model that supports the protection of natural resources of a region.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.4', 'Primary tourist resource', 'Tourist resources which were not originally intended for tourism. For example, natural areas such as forests and beaches or buildings such as temples and city walls.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.4', 'Resort sustainability', 'Environmental best practices such as waste management, energy saving, recycling of resources and reduction of water consumption are some of the ways a resort can be regarded as sustainable.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.4', 'Secondary tourist resource', 'Tourist resources that were deliberately built to attract tourists. For example, hotels, shopping destinations, restaurants, and theme parks.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.4', 'Sustainable tourism', 'A type of tourism that takes responsibility for, and balances its environmental, economic, and social impact.', 'Economic Development ');
-- TOPIC 3.5: 3.5 Energy
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Biogas', 'A gas such as methane that is produced by fermenting organic matter. We can use it as an energy source.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Biomass', 'Organic material from plants and animals, that can be burned as fuel or used to generate electricity.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Energy mix', 'A group of different energy sources from which secondary energy such as electricity is produced.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Energy security', 'The uninterrupted availability of energy sources to the population at affordable prices.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Fossil fuels', 'A natural, non-renewable energy source such as coal or gas, formed millions of years ago from the remains of living organisms.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Fuelwood', 'Wood that is burned as an energy source.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Geothermal energy', 'Renewable energy generated from the heat under the surface of the Earth.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Hydro-electric power (HEP)', 'Electricity generated by using the power of moving water.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Non-renewable energy', 'Energy that is produced from resources that will run out and not be replenished for millions of years. For example, oil, gas, and coal.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Primary energy demand', 'The total energy requirements of a country.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Renewable energy', 'Energy that is produced from resources that are not depleted and can be naturally and quickly replenished. For example, wind and solar power.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Secondary energy source', 'When primary energy (energy harvested directly from the natural source) is turned into a transportable form of energy. For example, when we burn coal in a power plant to generate electricity, the electricity is a form of secondary energy.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Solar energy', 'Electricity generated by using the energy of the sun.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Tidal and wave energy', 'Electricity that is generated using the energy of waves and tides.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.5', 'Wind energy', 'Electricity that is generated using the power of the wind.', 'Economic Development ');
-- TOPIC 3.6: 3.6 Water
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.6', 'Domestic', 'Related to water use in the home, for example drinking, cooking, and cleaning.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.6', 'Sewage', 'Human wastewater.', 'Economic Development ');
-- TOPIC 3.7: 3.7 Environmental Risks
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Aerosols', 'Tiny particles including ash, sulphur dioxide, and water vapour that a volcano ejects into the atmosphere during an eruption.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Afforestation', 'Planting trees in an area that has not recently had tree cover.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Biodiverse', 'An ecosystem that has a large variety of plant and animal life.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'CFCs', 'Chlorofluorocarbons are an industrial product. They are a stable chlorine molecule used in refrigeration and aerosol sprays. The production of CFCs has been banned internationally.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Desertification', 'The process by which vegetation in areas with low rainfall decreases and disappears.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Enhanced greenhouse effect', 'A process where an increase in the amount of greenhouse gases in the atmosphere from human activities causes Earth to heat up, as less re-radiated heat from solar radiation escapes into space.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Global warming potential (GWP)', 'A measure of how much a greenhouse gas is estimated to contribute to global warming over a specific time period compared to carbon dioxide.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Greenhouse gases', 'Gases in Earth''s atmosphere that trap heat by absorbing infrared radiation, and warm the planet. Examples include carbon dioxide and methane.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Natural greenhouse effect', 'A process where greenhouse gases in Earth''s atmosphere trap re-radiated heat from solar radiation and keep Earth warm.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Net zero', 'Reducing greenhouse gas emissions to a point where the greenhouse gases going into the atmosphere are balanced by removing them out of the atmosphere.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Noise pollution', 'Unwanted or disturbing sound in the environment that affects the health and well-being of humans.', 'Economic Development ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('3.7', 'Sustainable management', 'Managing an environment, resources, or processes in a way that meets the needs of the present day without compromising the needs of future generations.', 'Economic Development ');
-- TOPIC 4.1: 4.1 Geographical Skills
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Annotation', 'Detailed labels with an explanation of what is shown in the diagram.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Bearing', 'The angles formed by a line joining two points and the north and south line.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Categorical data', 'Data that describes information descriptively rather than numerically.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Compass', 'A geographical instrument with a pointer that shows magnetic north. It is used for finding direction.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Contour lines', 'Brown lines on the map that join together places of equal height. The height above sea level will be noted along some of the contour lines.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Difference', 'The result of subtracting one number from another.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Eastings', 'The eastwards measurement of distance. They are the vertical lines that run north to south on a map. They are the co-ordinates that stretch along the x-axis of the map.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Elevation', 'Height above a given level, for example, metres above sea level.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Geographical Information Systems (GIS)', 'A computer system for capturing, storing, checking, and displaying data related to positions on the Earth''s surface. GIS can show many different types of information on one map.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Gradient', 'The degree to which the land slopes. Hills have steep gradients and flat land has a gentle gradient.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Hypothesis', 'A precise, testable statement that a researcher makes. It predicts the outcome of a study that is designed to answer a specific question.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Interval', 'The difference in height above sea level between each contour line.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Key', 'An inset on a map that explains the symbols and provides a scale for the map.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Label', 'A short description used to identify a feature.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Northings', 'The northwards measurement of distance. They are the lines on a map that run horizontally, east to west, and show the distance to the equator. They are the co-ordinates that stretch along the y-axis of the map.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Outlier', 'A single data point that falls far outside the average value for a group of data.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Pilot study', 'A small-scale sample study that you can carry out to test the methods that you want to use in your proposed investigation.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Primary data', 'Data collected by the researchers themselves.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Quadrat', 'Square frames of a known size, such as 1m¬≤, that geographers place on the ground to measure abundance of plants or organisms in an area.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Quantitative data', 'Data that can be counted or measured in numerical values.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Random sampling', 'A method of sampling where you determine the person/point/site you want to sample through the use of random numbers.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Secondary data', 'Existing data that has been collected by in a previous study, by somebody else.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Spot height', 'Dots placed anywhere on a map, with a number next to them that indicates the exact height above sea level.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Systematic sampling', 'A method of sampling where you identify a regular pattern for sampling points in an investigation.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Trend', 'A general direction in which something is developing. A trend line is a line on a graph indicating the general relationship between two sets of data.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('4.1', 'Triangulation station', 'A small dot and a triangle on a map, with a number indicating height above sea level. These are also known as trig points and indicate the top of a mountain on a map.', 'Geographical Skills and Investigations  ');
-- TOPIC general: General/Multiple Topics
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('general', 'Archipelago', 'A group, chain, cluster, or collection of islands.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('general', 'Bottom-up development strategies', 'Small development decisions often led by local people with assistance from non-governmental organisations (NGOs).', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('general', 'Cholera', 'A diarrhoeal illness caused by eating food or drinking water contaminated with cholera bacteria.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('general', 'Congestion charge scheme', 'A transport management scheme where drivers of motor vehicles have to pay a charge for entering congestion charge zones.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('general', 'Disposable income', 'The amount of money available to a person after the deduction of taxes. Analysts often use this to measure consumer spending.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('general', 'Top-down development strategies', 'Development decisions made by governments or large companies, often associated with large scale projects.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('general', 'Infrastructure', 'Facilities and systems that allow a place to function, e.g. transportation, energy, and public buildings.', 'Geographical Skills and Investigations  ');
INSERT INTO teacher_definitions (topic_id, term, definition, theme) VALUES ('general', 'Remote work', 'When an employee has a flexible working arrangement with the employer, the employee is entitled to perform work at any alternative work site such as their home, or other suitable worksite, even outside of the country. This could be on a permanent or part time basis.', 'Geographical Skills and Investigations  ');
